use_case_id: "test"
choosen_model: 'LGBMClassifier'
logfile_name: 'log.log'

### dataset
DATASET:
            
    index_column: "contract_code"
    target_column: "flg_target"
    columns_to_filter_or_preprocess: []
    general_profiling_consent_column_name: flg_privacy_consent_profiling_general

    columns_to_keep: [
        'arpu_net',
        'avg_last_month_device_eth_ratio',
        'avg_last_month_device_wifi_24_ratio',
        'avg_last_month_entertainment_traffic',
        'avg_last_month_num_device_eth',
        'avg_last_month_num_tot_device',
        'avg_last_month_total_traffic_24',
        'avg_last_month_total_traffic_5',
        'avg_last_week_business_traffic_ratio',
        'avg_last_week_device_wifi_24_ratio',
        'avg_last_week_entertainment_traffic',
        'avg_last_week_entertainment_traffic_ratio',
        'avg_last_week_num_device_wifi_24',
        'avg_last_week_num_tot_device',
        'cluster_arpu_gross_tv',
        'cluster_arpu_net_tv',
        'cluster_std_last_month_business_traffic',
        'coverage_area_type',
        'num_days_after_last_call_3_months',
        'num_days_after_last_inbound_call',
        'des_line_type_la',
        'des_promo_category_tv',
        'des_voice_offer_inlife',
        'discount',
        'flg_case_closed_last_month',
        'flg_exit_fee_tv',
        'flg_high_churn_risk',
        'flg_intrattenimento_plus',
        'flg_invoice_view_ever',
        'flg_last_month_spot_recommendation',
        'flg_last_week_spot_recommendation',
        'flg_low_churn_risk',
        'flg_mop_inlife_postepay',
        'flg_mop_sales_unlike_inlife',
        'flg_pack_cinema',
        'flg_pdisc_tv',
        'flg_previous_fttc_speed_down_below_20mb',
        'last_month_speed_up',
        'last_reboot_reason',
        'main_reboot_last_month',
        'main_reboot_last_week',
        'max_last_month_business_traffic_ratio',
        'max_last_month_device_wifi_24_ratio',
        'max_last_month_device_wifi_5_ratio',
        'max_last_week_entertainment_traffic',
        'max_last_week_total_traffic_24',
        'num_evening_inbound_call',
        'num_morning_inbound_call',
        'num_short_inbound_calls',
        'num_calls_value_ta_lastmonth',
        'num_days_from_last_reboot',
        'num_inbound_calls_3_months',
        'num_reboot_last_week',
        'num_week_to_end_discount',
        'perc_discount_bb',
        'platform',
        'promo_classification',
        'sales_channel_sales',
        'scalar_arpu_net_tv',
        'scalar_cash_discount_tv',
        'scalar_perc_discount_tv',
        'std_last_month_business_traffic',
        'std_last_month_device_eth_ratio',
        'std_last_month_entertainment_traffic_ratio',
        'std_last_month_num_tot_device',
        'std_last_month_total_traffic',
        'std_last_week_device_wifi_24_ratio',
        'std_last_week_entertainment_traffic',
        'std_last_week_num_tot_device',
        'std_last_week_total_traffic',
        'technology_service_type_detail',
        'tenure_bb',
        'treatment_product',
        'voice_user_usage_3_months',
        'wholesaler',
        'date_kpis_reference',
        'date_kpis_run',
    ]
    
    converters:
    #    province: "str"

### preprocessing
PREPROCESS:
    freq_treshold: 0
    corr_treshold: 0.85
    filename: 'preprocess.pickle'

### model fitting without cross validation
MODEL:
    settings:
        test_size: 0.3
        random_state: 2022
        undersampling_version: -1 
    LGBMClassifier:
      filename: 'lgbm.pkl'
      filename_txt: 'lgbm.txt'
      params: {       
        'num_leaves': 30,
        'max_depth': 30,
        'learning_rate': 0.1,
        'n_estimators': 300,
        'early_stopping_rounds': 10,
        'seed': 2022,
        'deterministic': True,
        'metric': 'auc',
        'feature_fraction': 0.8,
      }

### feature importance 
FEATURE_IMPORTANCE:
    importance_type: 'gain'
    filename: 'feature_importance'

### shap Values
SHAP_VALUES:
    n_shaps: 5000
    importance_treshold: 0.0015
    type_shap: 'dot'  # violin, bar, dot
    filename: 'shap_values_'

## cross validation
CV:
    bayes_settings:
        param_space: {       
            'num_leaves': (30, 100),     # Range for num_leaves
            'max_depth': (5, 10),       # Range for max_depth
            'learning_rate': (0.1, 0.5),   # Range for learning_rate
            'n_estimators': (50, 200) 
        }
        n_iter: 5
        cv: 5
        n_jobs: -1
        scoring: 'recall'
